### PR TITLE
6 demo application with freertos tasks and priorities

### LINKED ISSUE #6: Demo application with FreeRTOS tasks
Make a demo application where multiple tasks are created and show how the scheduling is handled with same or different priorities.

### PR DESCRIPTION
**Pull request by iamFredNi**
example 2 completed

### CODE REVIEW

**Review by cicciord — CHANGES_REQUESTED** [review]
- Files in the root directory should not be present (FreeRTOSConfig.h, IntQueueTimer.c, IntQueueTimer.h)
- FreeRTOS Common Folder is copied in the Demo folder, while the rest of the FreeRTOS files are not. Choose only one approach, copy all files or don't copy any of them.
- main.c contains still all the code of the main_full code.

**Comment by iamFredNi** [comment]
> * Files in the root directory should not be present (FreeRTOSConfig.h, IntQueueTimer.c, IntQueueTimer.h)
> * FreeRTOS Common Folder is copied in the Demo folder, while the rest of the FreeRTOS files are not. Choose only one approach, copy all files or don't copy any of them.
> * main.c contains still all the code of the main_full code.

**Comment by iamFredNi** [comment]
@cicciord I fixed the project , take a look

**Comment by iamFredNi** [comment]
> * Files in the root directory should not be present (FreeRTOSConfig.h, IntQueueTimer.c, IntQueueTimer.h)
> * FreeRTOS Common Folder is copied in the Demo folder, while the rest of the FreeRTOS files are not. Choose only one approach, copy all files or don't copy any of them.
> * main.c contains still all the code of the main_full code.

I fixed the project, take a look @cicciord

**Pull request closed without merging**
